# Generated by Django 5.1.2 on 2026-03-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_action_b32d4d_idx",
            old_name="audit_log_action_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_target__219605_idx",
            old_name="audit_log_target_type_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_user_id_4dac76_idx",
            old_name="audit_log_user_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_created_ee0a56_idx",
            old_name="audit_log_created_idx",
        ),
    ]
