# Generated by Django 5.1.2 on 2024-11-05 11:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("api_token", models.CharField(max_length=255)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("telegram", "TELEGRAM"),
                            ("whatsapp", "WHATSAPP"),
                            ("website", "WEBSITE"),
                            ("instagram", "INSTAGRAM"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="assistant.assistant",
                    ),
                ),
            ],
            options={
                "db_table": "integration",
                "ordering": ["-created_time"],
            },
        ),
    ]
