# Generated by Django 5.1.2 on 2024-12-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="group_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
