# Generated by Django 5.1.2 on 2024-12-25 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0002_integration_group_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="group_id",
        ),
        migrations.CreateModel(
            name="TelegramGroupIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("group_id", models.CharField(max_length=255)),
                ("group_title", models.CharField(max_length=255)),
                (
                    "integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_group",
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "db_table": "telegram_group_integration",
            },
        ),
    ]
