# Generated by Django 5.1.2 on 2024-12-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0003_remove_integration_group_id_telegramgroupintegration"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramgroupintegration",
            name="lead_count",
            field=models.IntegerField(default=0),
        ),
    ]
