# Generated by Django 5.1.2 on 2024-12-28 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0004_telegramgroupintegration_lead_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramgroupintegration",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_group",
                to="integration.integration",
            ),
        ),
    ]
