# Generated by Django 5.1.2 on 2025-03-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0005_alter_telegramgroupintegration_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="instagram_user_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="integration",
            name="page_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="integration",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="integration",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
