# Generated by Django 5.1.2 on 2025-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "integration",
            "0006_integration_instagram_user_id_integration_page_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
