# Generated by Django 5.1.2 on 2025-04-10 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0007_integration_refresh_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="page_id",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="profile_picture",
        ),
    ]
