# Generated by Django 5.1.2 on 2025-04-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0008_remove_integration_page_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="instagram_account_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
