# Generated by Django 5.1.2 on 2025-04-10 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0009_integration_instagram_account_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="integration",
            old_name="username",
            new_name="instagram_username",
        ),
    ]
