# Generated by Django 5.1.2 on 2025-06-20 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0010_rename_username_integration_instagram_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('trigger_word', models.CharField(blank=True, max_length=255, null=True)),
                ('direct_message', models.TextField(blank=True, null=True)),
                ('is_commented', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_media', to='integration.integration')),
            ],
            options={
                'db_table': 'instagram_media',
                'ordering': ['-created_time'],
            },
        ),
    ]
