# Generated by Django 5.1.2 on 2025-06-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0011_instagrammedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrammedia',
            name='is_commented',
        ),
        migrations.RemoveField(
            model_name='instagrammedia',
            name='is_replied',
        ),
    ]
