# Generated by Django 5.1.2 on 2025-06-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0012_remove_instagrammedia_is_commented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammedia',
            name='is_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagrammedia',
            name='media_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
