# Generated by Django 5.1.2 on 2025-06-20 17:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0013_instagrammedia_is_all_instagrammedia_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTriggerWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('trigger_word', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'comment_trigger_word',
                'ordering': ['-created_time'],
            },
        ),
        migrations.RenameField(
            model_name='instagrammedia',
            old_name='is_all',
            new_name='is_respond_to_all_comments',
        ),
        migrations.RemoveField(
            model_name='instagrammedia',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='instagrammedia',
            name='direct_message',
        ),
        migrations.RemoveField(
            model_name='instagrammedia',
            name='trigger_word',
        ),
        migrations.CreateModel(
            name='InstagramCommentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('comment_message_template', models.TextField(blank=True)),
                ('private_message_template', models.TextField(blank=True)),
                ('instagram_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_comment_responses', to='integration.instagrammedia')),
                ('trigger_word', models.ManyToManyField(related_name='instagram_comment_responses', to='integration.commenttriggerword')),
            ],
            options={
                'db_table': 'instagram_comment_response',
                'ordering': ['-created_time'],
            },
        ),
    ]
