# Generated by Django 5.1.2 on 2025-06-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0014_commenttriggerword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramcommentresponse',
            old_name='trigger_word',
            new_name='trigger_words',
        ),
    ]
