# Generated by Django 5.1.2 on 2025-06-23 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0015_rename_trigger_word_instagramcommentresponse_trigger_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrammedia',
            name='integration',
        ),
        migrations.RemoveField(
            model_name='instagrammedia',
            name='is_respond_to_all_comments',
        ),
        migrations.RemoveField(
            model_name='instagrammedia',
            name='media_type',
        ),
        migrations.AddField(
            model_name='instagramcommentresponse',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_comment_responses', to='integration.integration'),
        ),
        migrations.AddField(
            model_name='instagramcommentresponse',
            name='is_respond_to_all_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='instagramcommentresponse',
            name='instagram_media',
        ),
        migrations.AddField(
            model_name='instagramcommentresponse',
            name='instagram_media',
            field=models.ManyToManyField(related_name='instagram_comment_responses', to='integration.instagrammedia'),
        ),
    ]
