# Generated by Django 5.1.2 on 2025-06-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0016_remove_instagrammedia_integration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammedia',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrammedia',
            name='children',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrammedia',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagrammedia',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagrammedia',
            name='media_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagrammedia',
            name='media_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagrammedia',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrammedia',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
