# Generated by Django 5.1.2 on 2025-06-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0017_instagrammedia_caption_instagrammedia_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammedia',
            name='media_type',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
