# Generated by Django 5.1.2 on 2025-06-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0018_alter_instagrammedia_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammedia',
            name='media_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
