# Generated by Django 5.1.2 on 2025-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0019_alter_instagrammedia_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammedia',
            name='media_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
