# Generated by Django 5.1.2 on 2025-06-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0020_alter_instagrammedia_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
