# Generated by Django 5.1.2 on 2025-07-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0021_alter_integration_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammedia',
            name='media_url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
