# Generated by Django 5.1.2 on 2025-09-11 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0033_lead_status"),
        ("integration", "0022_alter_instagrammedia_media_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="assistant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrations",
                to="assistant.assistant",
            ),
        ),
    ]
