# Generated by Django 5.1.2 on 2025-09-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0024_integration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcommentresponse',
            name='instagram_media',
            field=models.ManyToManyField(blank=True, null=True, related_name='instagram_comment_responses', to='integration.instagrammedia'),
        ),
    ]
