# Generated by Django 5.1.2 on 2025-09-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0025_alter_instagramcommentresponse_instagram_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcommentresponse',
            name='instagram_media',
            field=models.ManyToManyField(related_name='instagram_comment_responses', to='integration.instagrammedia'),
        ),
    ]
