# Generated by Django 5.1.2 on 2025-09-18 10:42

import apps.integration.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0026_alter_instagramcommentresponse_instagram_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentResponseButton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='instagramcommentresponse',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.integration.models.comment_response_image_path),
        ),
        migrations.AddField(
            model_name='instagramcommentresponse',
            name='extra_button',
            field=models.ManyToManyField(related_name='instagram_comment_responses', to='integration.commentresponsebutton'),
        ),
    ]
