# Generated by Django 5.1.2 on 2025-09-19 14:16

import apps.integration.models
import django.db.models.deletion
import shared.addons.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0027_commentresponsebutton_instagramcommentresponse_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramcommentresponse',
            name='extra_button',
        ),
        migrations.RemoveField(
            model_name='instagramcommentresponse',
            name='image',
        ),
        migrations.AddField(
            model_name='commentresponsebutton',
            name='type',
            field=models.CharField(blank=True, choices=shared.addons.enums.ButtonType.choices, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='commentresponsebutton',
            table='comment_response_btn',
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('flow_type', models.CharField(choices=shared.addons.enums.FlowType.choices, default='comment_response', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('comment_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='integration.instagramcommentresponse')),
            ],
            options={
                'db_table': 'flow',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('message_content', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(choices=shared.addons.enums.ActionType.choices, max_length=255)),
                ('condition_type', models.CharField(blank=True, choices=shared.addons.enums.ConditionType.choices, max_length=255, null=True)),
                ('message_image', models.ImageField(blank=True, null=True, upload_to=apps.integration.models.comment_response_image_path)),
                ('extra_button', models.ManyToManyField(related_name='steps', to='integration.commentresponsebutton')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='integration.flow')),
            ],
            options={
                'db_table': 'step',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('button_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='integration.commentresponsebutton')),
                ('from_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='integration.step')),
                ('to_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='integration.step')),
            ],
            options={
                'db_table': 'transition',
            },
        ),
        migrations.CreateModel(
            name='FlowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='integration.flow')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.step')),
            ],
            options={
                'db_table': 'flow_execution',
                'unique_together': {('flow', 'user_id')},
            },
        ),
    ]
