# Generated by Django 5.1.2 on 2025-09-21 08:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0028_remove_instagramcommentresponse_extra_button_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUserState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('account_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integration.step')),
            ],
            options={
                'db_table': 'instagram_user_state',
                'unique_together': {('account_id', 'user_id')},
            },
        ),
        migrations.DeleteModel(
            name='FlowExecution',
        ),
    ]
