# Generated by Django 5.1.2 on 2025-09-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0029_instagramuserstate_delete_flowexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='start_point',
            field=models.BooleanField(default=False),
        ),
    ]
