# Generated by Django 5.1.2 on 2025-09-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0030_step_start_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='action_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
