# Generated by Django 5.1.2 on 2025-10-07 07:40

import shared.addons.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0031_transition_action_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='action',
            field=models.CharField(choices=shared.addons.enums.ActionType.choices, default='message', max_length=255),
        ),
        migrations.AlterField(
            model_name='step',
            name='condition_type',
            field=models.CharField(choices=shared.addons.enums.ConditionType.choices, default='subscribed', max_length=255),
        ),
    ]
