# Generated by Django 5.1.2 on 2025-10-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0032_alter_step_action_alter_step_condition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='message_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
