# Generated by Django 5.1.2 on 2025-10-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0033_alter_step_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='end_point',
            field=models.BooleanField(default=False),
        ),
    ]
