# Generated by Django 5.1.2 on 2025-10-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0034_flow_total_count_step_count_step_end_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='is_comment_response',
            field=models.BooleanField(default=False),
        ),
    ]
