# Generated by Django 5.1.2 on 2025-10-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0035_integration_is_comment_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='api_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('telegram', 'TELEGRAM'), ('whatsapp', 'WHATSAPP'), ('website', 'WEBSITE'), ('instagram', 'INSTAGRAM'), ('bitrix24', 'BITRIX24'), ('amocrm', 'AMOCRM')], max_length=50),
        ),
    ]
