# Generated by Django 5.1.2 on 2025-10-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0036_alter_integration_api_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='api_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
