# Generated by Django 5.1.2 on 2025-10-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0037_alter_integration_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
