# Generated by Django 5.1.2 on 2025-11-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0038_integration_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('telegram', 'TELEGRAM'), ('whatsapp', 'WHATSAPP'), ('website', 'WEBSITE'), ('instagram', 'INSTAGRAM'), ('bitrix24', 'BITRIX24'), ('amocrm', 'AMOCRM'), ('billz', 'BILLZ')], max_length=50),
        ),
    ]
