# Generated by Django 5.1.2 on 2026-03-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0041_telegramgroupintegration_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentresponsebutton",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("web_url", "WEBURL"), ("postback", "POSTBACK")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="flow",
            name="flow_type",
            field=models.CharField(
                choices=[("comment_response", "COMMENT_RESPONSE")],
                default="comment_response",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="action",
            field=models.CharField(
                choices=[("condition", "CONDITION"), ("message", "MESSAGE")],
                default="message",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="condition_type",
            field=models.CharField(
                choices=[("subscribed", "SUBSCRIBED")],
                default="subscribed",
                max_length=255,
            ),
        ),
    ]
