# Generated by Django 5.1.2 on 2026-08-04 10:01

from django.db import migrations, models

import apps.integration.models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0043_integration_integration_ig_user_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='message_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.integration.models.comment_response_image_path),
        ),
    ]
