# Generated by Django 5.1.2 on 2026-08-04 05:23

import apps.shared.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0051_encrypt_secrets_and_pii'),
        ('integration', '0043_integration_integration_ig_user_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='api_token_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='api_token',
            field=apps.shared.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='metadata',
            field=apps.shared.fields.EncryptedJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='refresh_token',
            field=apps.shared.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['api_token_hash'], name='integration_token_hash_idx'),
        ),
    ]
