# Generated by Django 5.1.2 on 2026-08-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0044_alter_step_message_image'),
        ('integration', '0045_encrypt_integration_secret_data'),
    ]

    operations = [
    ]
