# Generated by Django 5.2.3 on 2026-03-11 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandingLead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=50)),
                (
                    "telegram_username",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "source_page",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("contacted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "landing_leads",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="LeadNotificationGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("group_id", models.CharField(max_length=100, unique=True)),
                (
                    "group_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "lead_notification_groups",
            },
        ),
    ]
