server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    access_log off;
    return 444;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    ssl_certificate     /etc/letsencrypt/live/api.aylo.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.aylo.uz/privkey.pem;

    access_log off;
    return 444;
}
