# Generated by Django 5.1.2 on 2026-08-17 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('conversation_id', models.UUIDField(db_index=True)),
                ('assistant_id', models.UUIDField(db_index=True)),
                ('initial_tier', models.CharField(choices=[('fast', 'FAST'), ('standard', 'STANDARD'), ('deep', 'DEEP')], max_length=16)),
                ('final_tier', models.CharField(choices=[('fast', 'FAST'), ('standard', 'STANDARD'), ('deep', 'DEEP')], max_length=16)),
                ('final_model', models.CharField(max_length=64)),
                ('routing_reason', models.CharField(blank=True, default='', max_length=128)),
                ('escalated', models.BooleanField(db_index=True, default=False)),
                ('escalation_reason', models.CharField(blank=True, default='', max_length=128)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cached_input_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('api_calls', models.IntegerField(default=0)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('duration_ms', models.IntegerField(default=0)),
                ('outcome', models.CharField(choices=[('ok', 'OK'), ('fallback', 'FALLBACK'), ('error', 'ERROR')], db_index=True, default='ok', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'agent_runs',
                'indexes': [models.Index(fields=['-created_time'], name='agent_runs_created_49c226_idx'), models.Index(fields=['assistant_id', '-created_time'], name='agent_runs_assista_5693f3_idx'), models.Index(fields=['-duration_ms'], name='agent_runs_duratio_310aa5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentRunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('sequence', models.IntegerField()),
                ('stage', models.CharField(db_index=True, default='act', max_length=16)),
                ('tier', models.CharField(choices=[('fast', 'FAST'), ('standard', 'STANDARD'), ('deep', 'DEEP')], max_length=16)),
                ('model', models.CharField(max_length=64)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cached_input_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('tools_duration_ms', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='shared.agentrun')),
            ],
            options={
                'db_table': 'agent_run_steps',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['run', 'sequence'], name='agent_run_s_run_id_9d3e9a_idx')],
            },
        ),
    ]
