# Generated by Django 5.1.2 on 2024-12-30 13:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("language", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "privacy_policy",
                "indexes": [
                    models.Index(fields=["title"], name="privacy_pol_title_604217_idx"),
                    models.Index(
                        fields=["language"], name="privacy_pol_languag_5ffbfc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("language", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "user_agreement",
                "indexes": [
                    models.Index(fields=["title"], name="user_agreem_title_026ce3_idx"),
                    models.Index(
                        fields=["language"], name="user_agreem_languag_7755cc_idx"
                    ),
                ],
            },
        ),
    ]
