# Generated by Django 5.1.2 on 2025-01-19 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_transaction_transaction_type_alter_card_is_default_and_more"),
        ("user", "0002_privacypolicy_useragreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pricing_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="payment.pricingpackage",
            ),
        ),
    ]
