# Generated by Django 5.1.2 on 2025-01-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_pricing_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="next_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_active",
            field=models.BooleanField(default=True),
        ),
    ]
