# Generated by Django 5.1.2 on 2025-01-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_next_payment_date_user_retry_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="used_request_count",
            field=models.IntegerField(default=0),
        ),
    ]
