# Generated by Django 5.1.2 on 2025-01-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_user_used_request_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription_active",
            field=models.BooleanField(default=False),
        ),
    ]
