# Generated by Django 5.1.2 on 2025-05-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_user_sub_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sub",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
