# Generated by Django 5.1.2 on 2025-05-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_sub_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_sub_31a3f8_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub',
        ),
    ]
