# Generated by Django 5.1.2 on 2025-05-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payment', '0008_paddlecustomer'),
        ('user', '0008_remove_user_user_sub_31a3f8_idx_remove_user_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['sub'], name='user_sub_31a3f8_idx'),
        ),
    ]
