# Generated by Django 5.1.2 on 2025-05-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_sub'),
        ('user', '0009_user_sub_user_user_sub_31a3f8_idx'),
    ]

    operations = [
    ]
