# Generated by Django 5.1.2 on 2025-05-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('super_admin', 'SUPER_ADMIN'), ('admin', 'ADMIN'), ('manager', 'MANAGER'), ('support_agent', 'SUPPORT_AGENT'), ('customer', 'CUSTOMER'), ('staff', 'STAFF')], default='customer', max_length=50),
        ),
    ]
