# Generated by Django 5.1.2 on 2025-05-20 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_feature_options_feature_icon_feature_is_active_and_more'),
        ('user', '0012_alter_user_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pricing_package',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='payment.subscription'),
        ),
    ]
