# Generated by Django 5.1.2 on 2025-05-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_user_pricing_package_user_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='next_payment_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='used_request_count',
        ),
    ]
