# Generated by Django 5.1.2 on 2025-05-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_user_next_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
