# Generated by Django 5.1.2 on 2025-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_remove_user_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("phone", "PHONE"),
                    ("email", "EMAIL"),
                    ("google", "GOOGLE"),
                    ("apple", "APPLE"),
                ],
                default="email",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
