# Generated by Django 5.1.2 on 2025-05-23 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_remove_subscription_user'),
        ('user', '0015_remove_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='payment.subscription'),
        ),
    ]
