# Generated by Django 5.1.2 on 2025-05-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_auth_type'),
        ('user', '0016_user_subscription'),
    ]

    operations = [
    ]
