# Generated by Django 5.1.2 on 2026-07-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payment', '0020_feature_name_ar_pricingpackage_description_ar_and_more'),
        ('user', '0019_remove_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='uniq_user_email_not_blank'),
        ),
    ]
