# Generated by Django 5.2.3 on 2026-03-10 17:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_uz", models.CharField(max_length=255, null=True)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("title_kk", models.CharField(max_length=255, null=True)),
                ("title_ar", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short description for SEO meta and cards",
                        max_length=500,
                    ),
                ),
                (
                    "excerpt_en",
                    models.TextField(
                        help_text="Short description for SEO meta and cards",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "excerpt_uz",
                    models.TextField(
                        help_text="Short description for SEO meta and cards",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "excerpt_ru",
                    models.TextField(
                        help_text="Short description for SEO meta and cards",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "excerpt_kk",
                    models.TextField(
                        help_text="Short description for SEO meta and cards",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "excerpt_ar",
                    models.TextField(
                        help_text="Short description for SEO meta and cards",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full blog post content in HTML or Markdown"
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        help_text="Full blog post content in HTML or Markdown",
                        null=True,
                    ),
                ),
                (
                    "content_uz",
                    models.TextField(
                        help_text="Full blog post content in HTML or Markdown",
                        null=True,
                    ),
                ),
                (
                    "content_ru",
                    models.TextField(
                        help_text="Full blog post content in HTML or Markdown",
                        null=True,
                    ),
                ),
                (
                    "content_kk",
                    models.TextField(
                        help_text="Full blog post content in HTML or Markdown",
                        null=True,
                    ),
                ),
                (
                    "content_ar",
                    models.TextField(
                        help_text="Full blog post content in HTML or Markdown",
                        null=True,
                    ),
                ),
                ("cover_image", models.URLField(blank=True, max_length=500, null=True)),
                ("author", models.CharField(default="Repli AI Team", max_length=100)),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tags for filtering"
                    ),
                ),
                (
                    "target_keyword",
                    models.CharField(
                        blank=True,
                        help_text="Primary SEO keyword",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (max 70 chars)",
                        max_length=70,
                        null=True,
                    ),
                ),
                (
                    "meta_title_en",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (max 70 chars)",
                        max_length=70,
                        null=True,
                    ),
                ),
                (
                    "meta_title_uz",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (max 70 chars)",
                        max_length=70,
                        null=True,
                    ),
                ),
                (
                    "meta_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (max 70 chars)",
                        max_length=70,
                        null=True,
                    ),
                ),
                (
                    "meta_title_kk",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (max 70 chars)",
                        max_length=70,
                        null=True,
                    ),
                ),
                (
                    "meta_title_ar",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (max 70 chars)",
                        max_length=70,
                        null=True,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO description (max 160 chars)",
                        max_length=160,
                        null=True,
                    ),
                ),
                (
                    "meta_description_en",
                    models.CharField(
                        blank=True,
                        help_text="SEO description (max 160 chars)",
                        max_length=160,
                        null=True,
                    ),
                ),
                (
                    "meta_description_uz",
                    models.CharField(
                        blank=True,
                        help_text="SEO description (max 160 chars)",
                        max_length=160,
                        null=True,
                    ),
                ),
                (
                    "meta_description_ru",
                    models.CharField(
                        blank=True,
                        help_text="SEO description (max 160 chars)",
                        max_length=160,
                        null=True,
                    ),
                ),
                (
                    "meta_description_kk",
                    models.CharField(
                        blank=True,
                        help_text="SEO description (max 160 chars)",
                        max_length=160,
                        null=True,
                    ),
                ),
                (
                    "meta_description_ar",
                    models.CharField(
                        blank=True,
                        help_text="SEO description (max 160 chars)",
                        max_length=160,
                        null=True,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "read_time",
                    models.PositiveIntegerField(
                        default=5, help_text="Estimated read time in minutes"
                    ),
                ),
                (
                    "internal_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of internal link objects: [{"label": "...", "section": "pricing"}]',
                    ),
                ),
            ],
            options={
                "db_table": "blog_post",
                "ordering": ["-published_at", "-created_time"],
            },
        ),
    ]
