# Generated by Django 5.1.2 on 2024-10-27 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "pricing_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payment.pricingpackage",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="companies", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=50)),
                ("notification_preferences", models.JSONField(default=dict)),
                ("escalation_rules", models.JSONField(default=dict)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "db_table": "settings",
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="company_name_b922ad_idx"),
        ),
        migrations.AddIndex(
            model_name="settings",
            index=models.Index(fields=["company"], name="settings_company_92a937_idx"),
        ),
        migrations.AddIndex(
            model_name="settings",
            index=models.Index(
                fields=["created_time"], name="settings_created_307617_idx"
            ),
        ),
    ]
