# Generated by Django 5.1.2 on 2024-11-05 11:17

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.shared.addons.enums


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantFileUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="assistant/files/")),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "assistant_file_upload",
                "ordering": ["created_time"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "OPEN"),
                            ("closed", "CLOSED"),
                            ("pending", "PENDING"),
                            ("escalated", "ESCALATED"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("thread_id", models.CharField(blank=True, max_length=255, null=True)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "conversation",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.CharField(
                        choices=apps.shared.addons.enums.SenderTypes.choices, max_length=10
                    ),
                ),
                ("message_content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "TEXT"),
                            ("image", "IMAGE"),
                            ("video", "VIDEO"),
                            ("audio", "AUDIO"),
                            ("file", "FILE"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=apps.shared.addons.enums.MessageStatuses.choices,
                        default="delivered",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_time"],
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=50)),
                ("notification_preferences", models.JSONField(default=dict)),
                ("escalation_rules", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "settings",
            },
        ),
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("company_name", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("english", "ENGLISH"),
                            ("russian", "RUSSIAN"),
                            ("uzbek", "UZBEK"),
                            ("kazakh", "KAZAKH"),
                        ],
                        default="english",
                        max_length=10,
                    ),
                ),
                (
                    "personality_style",
                    models.CharField(
                        choices=[
                            ("formal", "FORMAL"),
                            ("friendly", "FRIENDLY"),
                            ("professional", "PROFESSIONAL"),
                            ("casual", "CASUAL"),
                            ("informative", "INFORMATIVE"),
                        ],
                        default="professional",
                        max_length=255,
                    ),
                ),
                ("greeting_message", models.TextField(blank=True, null=True)),
                ("fallback_message", models.TextField(blank=True, null=True)),
                (
                    "assistant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pricing_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistants",
                        to="payment.pricingpackage",
                    ),
                ),
            ],
            options={
                "db_table": "assistant",
            },
        ),
    ]
