# Generated by Django 5.1.2 on 2024-11-02 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "ENGLISH"),
                            ("ru", "RUSSIAN"),
                            ("uz", "UZBEK"),
                            ("kk", "KAZAKH"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "personality_style",
                    models.CharField(
                        choices=[
                            ("formal", "FORMAL"),
                            ("friendly", "FRIENDLY"),
                            ("professional", "PROFESSIONAL"),
                            ("casual", "CASUAL"),
                            ("informative", "INFORMATIVE"),
                        ],
                        default="professional",
                        max_length=255,
                    ),
                ),
                ("greeting_message", models.TextField(blank=True, null=True)),
                ("fallback_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "assistant",
            },
        ),
    ]
