# Generated by Django 5.1.2 on 2024-11-02 14:22

import django.db.models.deletion
import django.utils.timezone
import shared.addons.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "OPEN"),
                            ("closed", "CLOSED"),
                            ("pending", "PENDING"),
                            ("escalated", "ESCALATED"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=255, unique=True
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="assistant.assistant",
                    ),
                ),
            ],
            options={
                "db_table": "conversation",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.CharField(
                        choices=shared.addons.enums.SenderTypes.choices, max_length=10
                    ),
                ),
                ("message_content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "TEXT"),
                            ("image", "IMAGE"),
                            ("video", "VIDEO"),
                            ("audio", "AUDIO"),
                            ("file", "FILE"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=shared.addons.enums.MessageStatuses.choices,
                        default="delivered",
                        max_length=15,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="assistant.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_time"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["session_id"], name="conversatio_session_1a03f0_idx"
            ),
        ),
    ]
