# Generated by Django 5.1.2 on 2024-11-03 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0002_conversation_message_and_more"),
        ("payment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="assistant",
        #     name="company",
        # ),
        migrations.AddField(
            model_name="assistant",
            name="company_name",
            field=models.CharField(default="repliuz", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assistant",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistant",
            name="pricing_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assistants",
                to="payment.pricingpackage",
            ),
        ),
        migrations.AddField(
            model_name="assistant",
            name="role",
            field=models.CharField(default="repliuz", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assistant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
