# Generated by Django 5.1.2 on 2024-11-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="telegram_user_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
