# Generated by Django 5.1.2 on 2024-11-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0003_conversation_telegram_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
