# Generated by Django 5.1.2 on 2024-11-03 04:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0003_remove_assistant_company_assistant_company_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=50)),
                ("notification_preferences", models.JSONField(default=dict)),
                ("escalation_rules", models.JSONField(default=dict)),
                (
                    "assistant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="assistant.assistant",
                    ),
                ),
            ],
            options={
                "db_table": "settings",
            },
        ),
    ]
