# Generated by Django 5.1.2 on 2024-11-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0004_conversation_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="platform",
            field=models.CharField(
                choices=[
                    ("telegram", "TELEGRAM"),
                    ("whatsapp", "WHATSAPP"),
                    ("website", "WEBSITE"),
                    ("instagram", "INSTAGRAM"),
                    ("email", "EMAIL"),
                    ("sms", "SMS"),
                    ("phone", "PHONE"),
                    ("other", "OTHER"),
                ],
                default="telegram",
                max_length=50,
            ),
        ),
    ]
