# Generated by Django 5.1.2 on 2024-11-03 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0004_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantFileUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="assistant/files/")),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "assistant_file_upload",
                "ordering": ["created_time"],
            },
        ),
        migrations.RemoveIndex(
            model_name="conversation",
            name="conversatio_session_1a03f0_idx",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="session_id",
        ),
        migrations.AddField(
            model_name="assistant",
            name="assistant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="thread_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="assistantfileupload",
            name="assistant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="assistant.assistant",
            ),
        ),
    ]
