# Generated by Django 5.1.2 on 2024-11-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0005_conversation_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
