# Generated by Django 5.1.2 on 2024-11-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0005_assistantfileupload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="language",
            field=models.CharField(
                choices=[
                    ("english", "ENGLISH"),
                    ("russian", "RUSSIAN"),
                    ("uzbek", "UZBEK"),
                    ("kazakh", "KAZAKH"),
                ],
                default="english",
                max_length=10,
            ),
        ),
    ]
