# Generated by Django 5.1.2 on 2024-12-10 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0006_assistant_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
    ]
