# Generated by Django 5.1.2 on 2024-12-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0007_alter_message_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="wait_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
