# Generated by Django 5.1.2 on 2024-12-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0008_assistant_wait_message"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_time"], name="messages_created_0f66dd_idx"
            ),
        ),
    ]
