# Generated by Django 5.1.2 on 2025-01-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0009_message_messages_created_0f66dd_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="vector_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
