# Generated by Django 5.1.2 on 2025-01-19 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0010_assistant_vector_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assistant",
            name="pricing_package",
        ),
    ]
