# Generated by Django 5.1.2 on 2025-04-12 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0011_remove_assistant_pricing_package"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="telegram_user_id",
            new_name="user_id",
        ),
    ]
