# Generated by Django 5.1.2 on 2025-05-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0012_rename_telegram_user_id_conversation_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantfileupload',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assistantfileupload',
            name='website_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
