# Generated by Django 5.1.2 on 2025-05-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0013_assistantfileupload_telegram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantfileupload',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='assistantfileupload',
            name='website_link',
        ),
    ]
