# Generated by Django 5.1.2 on 2025-05-08 08:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0014_remove_assistantfileupload_telegram_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('registered', 'REGISTERED'), ('delivered', 'DELIVERED'), ('lost', 'LOST')], default='new', max_length=255)),
                ('platform', models.CharField(choices=[('telegram', 'TELEGRAM'), ('whatsapp', 'WHATSAPP'), ('website', 'WEBSITE'), ('instagram', 'INSTAGRAM'), ('email', 'EMAIL'), ('sms', 'SMS'), ('phone', 'PHONE'), ('other', 'OTHER')], max_length=255)),
            ],
            options={
                'db_table': 'leads',
            },
        ),
        migrations.AlterField(
            model_name='assistant',
            name='role',
            field=models.CharField(choices=[('sales agent', 'SALES_AGENT'), ('support agent', 'SUPPORT_AGENT'), ('operator', 'OPERATOR'), ('customer service', 'CUSTOMER_SERVICE')], max_length=50),
        ),
    ]
