# Generated by Django 5.1.2 on 2025-05-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0015_lead_alter_assistant_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lead",
        ),
        migrations.AlterField(
            model_name="assistant",
            name="role",
            field=models.CharField(max_length=50),
        ),
    ]
