# Generated by Django 5.1.2 on 2025-05-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0016_delete_lead_alter_assistant_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="assistant/audio/"),
        ),
    ]
