# Generated by Django 5.1.2 on 2025-05-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0017_message_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="audio_file",
            field=models.FileField(
                blank=True, null=True, upload_to="assistant/conversation/audio/"
            ),
        ),
    ]
