# Generated by Django 5.1.2 on 2025-05-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0018_alter_message_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.CharField(
                choices=[
                    ("assistant", "ASSISTANT"),
                    ("user", "USER"),
                    ("admin", "ADMIN"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("delivered", "DELIVERED"),
                    ("seen", "SEEN"),
                    ("responded", "RESPONDED"),
                ],
                default="delivered",
                max_length=15,
            ),
        ),
    ]
