# Generated by Django 5.1.2 on 2025-05-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0019_alter_message_sender_alter_message_status'),
        ('assistant', '0019_assistant_created_by'),
    ]

    operations = [
    ]
