# Generated by Django 5.1.2 on 2025-05-16 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0020_merge_20250516_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('telegram', 'TELEGRAM'), ('whatsapp', 'WHATSAPP'), ('website', 'WEBSITE'), ('instagram', 'INSTAGRAM'), ('email', 'EMAIL'), ('sms', 'SMS'), ('phone', 'PHONE'), ('other', 'OTHER')], default='telegram', max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('contacted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lead',
            },
        ),
    ]
