# Generated by Django 5.1.2 on 2025-05-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0021_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantfileupload',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
