# Generated by Django 5.1.2 on 2025-05-19 13:49

from django.db import migrations, models

import apps.assistant.models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0022_assistantfileupload_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='role',
            field=models.CharField(default='sales, support, and operations', max_length=50),
        ),
        migrations.AlterField(
            model_name='assistantfileupload',
            name='file',
            field=models.FileField(upload_to=apps.assistant.models.assistant_file_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.assistant.models.assistant_audio_path),
        ),
    ]
