# Generated by Django 5.1.2 on 2025-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0023_alter_assistant_role_alter_assistantfileupload_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.AddField(
            model_name='message',
            name='input_token',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='output_token',
            field=models.IntegerField(default=0),
        ),
    ]
