# Generated by Django 5.1.2 on 2025-05-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0024_remove_lead_source_message_input_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='input_token',
            new_name='input_tokens',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='output_token',
            new_name='output_tokens',
        ),
    ]
