# Generated by Django 5.1.2 on 2025-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0025_rename_input_token_message_input_tokens_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="company_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="assistant",
            name="role",
            field=models.CharField(
                default="sales, support, and operations", max_length=100
            ),
        ),
    ]
