# Generated by Django 5.1.2 on 2025-06-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0027_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='client_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='client_phone_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
