# Generated by Django 5.1.2 on 2025-06-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0028_conversation_client_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
