# Generated by Django 5.1.2 on 2025-07-03 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0029_assistant_ai_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='assistant.assistant'),
        ),
    ]
