# Generated by Django 5.1.2 on 2025-06-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0029_assistant_ai_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantfileupload',
            name='google_sheet_doc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
