# Generated by Django 5.1.2 on 2025-06-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0030_assistantfileupload_google_sheet_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantfileupload',
            name='file_type',
            field=models.CharField(blank=True, choices=[('google_spreadsheet', 'GOOGLE_SPREADSHEET'), ('google_document', 'GOOGLE_DOCUMENT')], max_length=255, null=True),
        ),
    ]
