# Generated by Django 5.1.2 on 2025-07-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0030_lead_assistant'),
        ('assistant', '0031_assistantfileupload_file_type'),
    ]

    operations = [
    ]
