# Generated by Django 5.1.2 on 2025-07-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0032_merge_20250715_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('contacted', 'CONTACTED'), ('success', 'SUCCESS'), ('rejected', 'REJECTED'), ('unreachable', 'UNREACHABLE')], default='new', max_length=255),
        ),
    ]
