# Generated by Django 5.1.2 on 2025-09-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0033_lead_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="user_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="platform",
            field=models.CharField(
                choices=[
                    ("telegram", "TELEGRAM"),
                    ("whatsapp", "WHATSAPP"),
                    ("website", "WEBSITE"),
                    ("instagram", "INSTAGRAM"),
                    ("email", "EMAIL"),
                    ("sms", "SMS"),
                    ("phone", "PHONE"),
                    ("other", "OTHER"),
                ],
                default="telegram",
                max_length=255,
            ),
        ),
    ]
