# Generated by Django 5.1.2 on 2025-09-21 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0034_conversation_user_name_lead_platform"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="user_name",
            new_name="username",
        ),
    ]
