# Generated by Django 5.1.2 on 2025-09-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0035_rename_user_name_conversation_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
