# Generated by Django 5.1.2 on 2025-09-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0036_lead_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('russian', 'RUSSIAN'), ('uzbek', 'UZBEK'), ('kazakh', 'KAZAKH')], default='english', max_length=50),
        ),
    ]
