# Generated by Django 5.1.2 on 2025-09-23 10:36

import django.contrib.postgres.fields
from django.db import migrations, models


def convert_char_to_array(apps, schema_editor):
    Assistant = apps.get_model("assistant", "Assistant")
    for assistant in Assistant.objects.all():
        if isinstance(assistant.language, str) and assistant.language:
            assistant.language = {assistant.language}
            assistant.save(update_fields=["language"])

class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0037_alter_assistant_language'),
    ]

    operations = [
        migrations.RunPython(convert_char_to_array, reverse_code=migrations.RunPython.noop),

        migrations.AlterField(
            model_name='assistant',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('english', 'ENGLISH'),
                        ('russian', 'RUSSIAN'),
                        ('uzbek', 'UZBEK'),
                        ('kazakh', 'KAZAKH')
                    ],
                    max_length=10
                ),
                blank=True,
                default=list,
                size=None
            ),
        ),
    ]
