# Generated by Django 5.1.2 on 2025-09-23 11:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0038_alter_assistant_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='steps',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('english', 'ENGLISH'), ('russian', 'RUSSIAN'), ('uzbek', 'UZBEK'), ('kazakh', 'KAZAKH')], max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
