# Generated by Django 5.1.2 on 2025-09-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0039_assistant_steps_alter_assistant_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='steps',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
