# Generated by Django 5.1.2 on 2025-09-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0040_alter_assistant_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'NEW'), ('engaged', 'ENGAGED'), ('partial_info', 'PARTIAL_INFO'), ('qualified', 'QUALIFIED'), ('rejected', 'REJECTED'), ('unreachable', 'UNREACHABLE')], default='new', max_length=255),
        ),
    ]
