# Generated by Django 5.1.2 on 2025-10-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0041_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantfileupload',
            name='file_id',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
