# Generated by Django 5.1.2 on 2026-01-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0042_assistantfileupload_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
