# Generated by Django 5.1.2 on 2026-01-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0043_assistant_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='web_search_tool',
            field=models.BooleanField(default=False),
        ),
    ]
