# Generated by Django 5.1.2 on 2026-01-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0044_conversation_web_search_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='web_search_tool',
        ),
        migrations.AddField(
            model_name='assistant',
            name='web_search_tool',
            field=models.BooleanField(default=False),
        ),
    ]
