# Generated by Django 5.1.2 on 2026-03-31 03:52

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0047_prompttemplate_assistant_prompt_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUpConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "target_statuses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=15),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "assistant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up_config",
                        to="assistant.assistant",
                    ),
                ),
            ],
            options={
                "db_table": "follow_up_config",
            },
        ),
        migrations.CreateModel(
            name="FollowUpStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("stage_number", models.PositiveIntegerField()),
                ("delay_hours", models.PositiveIntegerField()),
                ("message_template", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="assistant.followupconfig",
                    ),
                ),
            ],
            options={
                "db_table": "follow_up_stage",
                "ordering": ["stage_number"],
                "unique_together": {("config", "stage_number")},
            },
        ),
        migrations.CreateModel(
            name="FollowUpLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("sent", "SENT"),
                            ("cancelled", "CANCELLED"),
                            ("failed", "FAILED"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up_logs",
                        to="assistant.conversation",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="assistant.followupstage",
                    ),
                ),
            ],
            options={
                "db_table": "follow_up_log",
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="follow_up_l_status_de2ea6_idx",
                    )
                ],
                "unique_together": {("conversation", "stage")},
            },
        ),
    ]
