# Generated by Django 5.1.2 on 2026-07-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0048_followupconfig_followupstage_followuplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='instructions_version',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='previous_response_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
