# Generated by Django 5.1.2 on 2026-08-04 06:39

import apps.assistant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0050_conversation_conv_assistant_user_token_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantfileupload',
            name='file',
            field=models.FileField(max_length=255, upload_to=apps.assistant.models.assistant_file_path),
        ),
    ]
