# Generated by Django 5.1.2 on 2026-08-04 05:23

import apps.shared.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0050_conversation_conv_assistant_user_token_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='client_full_name',
            field=apps.shared.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='client_phone_email',
            field=apps.shared.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=apps.shared.fields.EncryptedTextField(),
        ),
    ]
