# Generated by Django 5.1.2 on 2026-08-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0051_alter_assistantfileupload_file'),
        ('assistant', '0052_encrypt_conversation_and_message_data'),
    ]

    operations = [
    ]
