# Generated by Django 5.1.2 on 2026-08-19 06:10

from django.db import migrations, models


def backfill_index_status(apps, schema_editor):
    """Existing rows are not pending — they were indexed by the old inline path.

    Leaving them at the `pending` default would make every document already in a
    vector store look unindexed to the client, and any UI that offers a retry on
    `failed`/`pending` would re-upload the whole knowledge base. A row that has a
    `file_id` is in the store by definition; one that never got one failed.
    """
    AssistantFileUpload = apps.get_model("assistant", "AssistantFileUpload")
    AssistantFileUpload.objects.exclude(file_id__isnull=True).exclude(
        file_id=""
    ).update(index_status="indexed")
    AssistantFileUpload.objects.filter(file_id__isnull=True).update(
        index_status="failed"
    )
    AssistantFileUpload.objects.filter(file_id="").update(index_status="failed")


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0053_merge_20260816_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantfileupload',
            name='index_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('indexing', 'INDEXING'), ('indexed', 'INDEXED'), ('failed', 'FAILED'), ('skipped', 'SKIPPED')], default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_index_status, migrations.RunPython.noop),
    ]
