# Generated by Django 5.1.2 on 2025-07-29 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0032_merge_20250715_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('database_type', models.CharField(blank=True, choices=[('mysql', 'MYSQL'), ('postgresql', 'POSTGRESQL'), ('sqlite', 'SQLITE'), ('mssql', 'MSSQL'), ('oracle', 'ORACLE')], max_length=255, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('password_encrypted', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('database_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistant.assistant')),
            ],
            options={
                'verbose_name': 'Database Connection',
                'verbose_name_plural': 'Database Connections',
            },
        ),
    ]
