# Generated by Django 5.1.2 on 2025-01-18 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricingpackage",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AddField(
            model_name="pricingpackage",
            name="currency",
            field=models.CharField(
                choices=[
                    ("uzs", "UZS"),
                    ("usd", "USD"),
                    ("rub", "RUB"),
                    ("eur", "EUR"),
                    ("kzt", "KZT"),
                ],
                default="uzs",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("card_token", models.TextField()),
                ("card_number", models.CharField(max_length=16)),
                ("expiry_date", models.CharField(max_length=10)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("color", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Card",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("payme", "PAYME"),
                            ("click", "CLICK"),
                            ("paynet", "PAYNET"),
                            ("uzum", "UZUM"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("success", "SUCCESS"),
                            ("failed", "FAILED"),
                            ("cancelled", "CANCELLED"),
                            ("refunded", "REFUNDED"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("uzs", "UZS"),
                            ("usd", "USD"),
                            ("rub", "RUB"),
                            ("eur", "EUR"),
                            ("kzt", "KZT"),
                        ],
                        default="uzs",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
                "ordering": ["-created_time"],
            },
        ),
    ]
