# Generated by Django 5.1.2 on 2025-01-18 18:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payment",
            "0002_alter_pricingpackage_options_pricingpackage_currency_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[("deposit", "DEPOSIT"), ("withdraw", "WITHDRAW")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="is_default",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "DRAFT"),
                    ("success", "SUCCESS"),
                    ("failed", "FAILED"),
                    ("cancelled", "CANCELLED"),
                    ("refunded", "REFUNDED"),
                ],
                default="draft",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("uzs", "UZS"),
                            ("usd", "USD"),
                            ("rub", "RUB"),
                            ("eur", "EUR"),
                            ("kzt", "KZT"),
                        ],
                        default="uzs",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "balance",
            },
        ),
    ]
