# Generated by Django 5.1.2 on 2025-01-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_transaction_transaction_type_alter_card_is_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingpackage",
            name="request_count",
            field=models.IntegerField(default=0),
        ),
    ]
