# Generated by Django 5.1.2 on 2025-01-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_pricingpackage_request_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingpackage",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="pricing_packages", to="payment.feature"
            ),
        ),
    ]
