# Generated by Django 5.1.2 on 2025-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_alter_pricingpackage_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_recurrent",
            field=models.BooleanField(default=False),
        ),
    ]
