# Generated by Django 5.1.2 on 2025-01-20 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_card_is_recurrent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="is_recurrent",
        ),
    ]
