# Generated by Django 5.1.2 on 2025-05-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_paddlecustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaddleCustomer',
        ),
    ]
