# Generated by Django 5.1.2 on 2025-05-20 07:12

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_delete_paddlecustomer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='duration_days',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
        # migrations.AddField(
        #     model_name='transaction',
        #     name='pricing_package',
        #     field=models.ForeignKey(default=20250908, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.pricingpackage'),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='transaction',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pricingpackage',
            name='request_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_subscription_active', models.BooleanField(default=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('used_request_count', models.IntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('grace_period_days', models.IntegerField(default=0)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pricing_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payment.pricingpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription',
                'ordering': ['-created_time'],
            },
        ),
    ]
