# Generated by Django 5.1.2 on 2025-05-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_feature_options_feature_icon_feature_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pricing_package',
        ),
    ]
