# Generated by Django 5.1.2 on 2025-05-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remove_transaction_pricing_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
    ]
