# Generated by Django 5.1.2 on 2025-05-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_remove_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingpackage',
            name='type',
            field=models.CharField(choices=[('free', 'FREE'), ('custom', 'CUSTOM'), ('pro', 'PRO')], default='free', max_length=50, null=True),
        ),
    ]
