# Generated by Django 5.1.2 on 2025-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_pricingpackage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_subscription_active',
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('cancelled', 'CANCELLED')], default='inactive', max_length=100),
        ),
    ]
