# Generated by Django 5.1.2 on 2025-05-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_remove_subscription_is_subscription_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='used_request_count',
            new_name='have_request_count',
        ),
    ]
