# Generated by Django 5.1.2 on 2025-05-28 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_rename_used_request_count_subscription_have_request_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='have_request_count',
        ),
        migrations.AddField(
            model_name='subscription',
            name='remained_request_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
