# Generated by Django 5.1.2 on 2025-05-28 11:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_remove_subscription_have_request_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('success', 'SUCCESS'), ('failed', 'FAILED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], max_length=100)),
                ('retry_date', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_payments', to='payment.subscription')),
            ],
            options={
                'db_table': 'retry_payment',
                'ordering': ['-created_time'],
            },
        ),
    ]
