# Generated by Django 5.1.2 on 2025-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_retrypayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='description',
        ),
        migrations.AddField(
            model_name='feature',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='description_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
