# Generated by Django 5.1.2 on 2025-07-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_alter_balance_user_alter_card_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingpackage',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
