# Generated by Django 5.1.2 on 2026-08-04 05:23

from django.db import migrations

import apps.shared.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_feature_name_ar_pricingpackage_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_token',
            field=apps.shared.fields.EncryptedTextField(),
        ),
    ]
