# Generated by Django 5.1.2 on 2026-08-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_custompackagerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingpackage',
            name='type',
            field=models.CharField(choices=[('free', 'FREE'), ('custom', 'CUSTOM'), ('basic', 'BASIC'), ('pro', 'PRO')], default='free', max_length=50, null=True),
        ),
    ]
