name: Deployment for production

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: [self-hosted, linux, gcp]
    steps:
      - uses: actions/checkout@v4
      - name: Load env
        run: cp /home/mukhammad.irmatov/backend_drf/.secrets/.env .
      - name: Blue/Green Deploy
        run: |
          chmod +x deployment/deploy.sh
          ./deployment/deploy.sh
