name: Deployment

on:
  push:
    branches:
      - main
      - dev

    paths-ignore:
      - "README.md"

jobs:
  deploy-prod:
    defaults:
        run:
          working-directory: ${{ github.workspace }}
    if: github.ref == 'refs/heads/main'
    name: Deploy

    runs-on: [self-hosted, repli-runner]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Print github.ref
        run: echo 'github.ref is: ${{ github.ref }}'

      - name: Deploy using docker compose
        run: |
            cp /home/mukhammad/.secrets/.env .
            docker compose down
            docker compose up --build -d
            yes | docker image prune

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    name: Deploy to Development
    runs-on: [self-hosted, dev-runner]  # label for Server B
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Print github.ref
        run: echo 'github.ref is: ${{ github.ref }}'

      - name: Deploy with Docker Compose
        run: |
          cp /home/shahzod/.secrets/.env .
          docker compose down
          docker compose up --build -d
          yes | docker image prune